### ISSUE TITLE
mso_schema_site fails when multiple resources are configured at the same time

### ISSUE THREAD

**Issue by adealdag** [CiscoDevNet/terraform-provider-mso#49] opened 2021-09-10 19:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/aci v0.7.1
+ provider registry.terraform.io/ciscodevnet/mso v0.2.1

### MSO version

Version: 3.4(1a) running on top of ND Version 2.0(2h)

### APIC version and APIC Platform for Site Level Resources

* V 5.2.2f, APIC on-prem

### Affected Resource(s)

* mso_schema_site (resource)

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aci = {
      source  = "CiscoDevNet/aci"
      version = "0.7.1"
    }
    mso = {
      source  = "CiscoDevNet/mso"
      version = "0.2.1"
    }
  }
}

provider "mso" {
  username = var.mso_username
  password = var.mso_password
  url      = var.mso_url
  insecure = true
  platform = "nd"
}

resource "mso_tenant" "demo" {
  name         = "ms_prod_tn"
  display_name = "ms_prod_tn"

  site_associations {
    site_id = local.site1
  }

  site_associations {
    site_id = local.site2
  }

  user_associations {
    user_id = local.current_user
  }

  user_associations {
    user_id = local.admin_user
  }
}

# Schema and Templates
resource "mso_schema" "ms_prod" {
  name          = "ms_prod_schema"
  template_name = "stretched"
  tenant_id     = mso_tenant.demo.id
}

resource "mso_schema_template" "ms_prod_site1_only" {
  schema_id = mso_schema.ms_prod.id
  name = "${lower(var.site1)}_only"
  display_name = "${lower(var.site1)}_only"
  tenant_id = mso_tenant.demo.id
}

resource "mso_schema_template" "ms_prod_site2_only" {
  schema_id = mso_schema.ms_prod.id
  name = "${lower(var.site2)}_only"
  display_name = "${lower(var.site2)}_only"
  tenant_id = mso_tenant.demo.id
}

resource "mso_schema_site" "schema_site_1_tpl1" {
  schema_id       =  mso_schema.ms_prod.id
  site_id         =  local.site1
  template_name   =  mso_schema.ms_prod.template_name
}

resource "mso_schema_site" "schema_site_1_tpl2" {
  schema_id       =  mso_schema.ms_prod.id
  site_id         =  local.site1
  template_name   =  mso_schema_template.ms_prod_site1_only.id
}

resource "mso_schema_site" "schema_site_2_tpl1" {
  schema_id       =  mso_schema.ms_prod.id
  site_id         =  local.site2
  template_name   =  mso_schema.ms_prod.template_name
}

}
```

### Debug Output

[Terraform Apply Output](https://gist.github.com/adealdag/9bc5883cc00e2af7ccca5b7afa0315ac)

[Provider Logs](https://gist.github.com/adealdag/7fc3a783af3e2e23249a4c19361f67d5)

### Expected Behavior

mso_schema_site should associate both sites with the defined templates in one apply without failing

### Actual Behavior

Terraform apply only manages to associate one site/template at a time and then fails, hence needing multiple applies.

### Steps to Reproduce

terraform plan or apply using the code above

1. `terraform apply`

### Important Factoids

Running NDO on top of vND

### References

* #0000

**Comment by anvitha-jain** [comment] 2021-09-21 18:08
Duplicate of #3

**Comment by lhercot** [comment] 2021-10-29 19:08
Closing as duplicate. We will update #3 when this is fixed.

**Closed by lhercot** 2021-10-29 19:08 UTC
Labels: bug, duplicate
