### ISSUE TITLE
Many BD declared modified after a static port configuration on EPG.

### ISSUE THREAD

**Issue by apellini** [CiscoDevNet/terraform-provider-mso#105] opened 2022-02-17 23:42 UTC
### MSO version

* V 2.2(3j)

### APIC version and APIC Platform for Site Level Resources

* V 4.2(3I) and on-prem

### Affected Resource(s)

* mso_schema_template_bd

### Terraform Configuration Files

```hcl
resource "mso_schema_template_bd" "bd" {
  schema_id              = 612g33f71100004d44ef719g
  template_name          = Template1
  name                   = BD_XXXX
  display_name           = BD_XXXX
  vrf_name               = VRF_A
  layer2_unknown_unicast = flood
  vrf_schema_id          = 5e78866d13eeedd5f441de19
  vrf_template_name      = Template1
}

```
### Expected Behavior
Install completed no further deploy needed.

### Actual Behavior
After deploy to site, with another tool we have configured some Static Ports on one EPG and after that all BD previously configured with terraform module are marked as updated with (InterSiteBumTrafficAllow as unchecked is deleted).

We have also compared configuration on APIC and we see that on these BDs only PIM flag is removed after deploy to site.

**Comment by xinyuezhao** [comment] 2022-03-24 18:01
Hi @apellini, we are working on this issue but we are not able to reproduce it. 
Would you mind sharing with us what tool you used to configure Static Ports and what changes you made(would be better if you can provider configuration file for that), and also where did you make those changes, through MSO or APIC?

**Comment by apellini** [comment] 2022-03-25 07:23
For configuring static ports we use an ansible playbook. All configurations are applied to MSO.

**Comment by lhercot** [comment] 2022-03-25 11:03
Could you share the relevant part of that playbook?

**Comment by lhercot** [comment] 2022-03-28 16:46
@apellini

**Comment by apellini** [comment] 2022-03-28 16:58
below:

'''YAML
- name: Add static port to a site EPG from csv
      cisco.mso.mso_schema_site_anp_epg_staticport:
        host: "{{ mso_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        schema: "{{ item.SCHEMA }}"
        site: "{{ item.SITE }}"
        template: "{{ item.TEMPLATEAPP }}"
        anp: "{{ item.AP }}"
        epg: "{{ item.EPG }}"
        type: "{{ item.TYPE }}"
        pod: "{{ item.POD }}"
        leaf: "{{ item.LEAF }}"
        path: "{{ item.PORT }}"
        vlan: "{{ item.VLAN | int }}"
        mode: "{{ item.MODE }}"
        deployment_immediacy: immediate
        state: present
        validate_certs: false
        use_proxy: no
      delegate_to: localhost
      retries: 3
      until: static_port is not failed
      register: static_port
      loop: "{{ csvread.list }}"
      loop_control:
        loop_var: item
'''

**Comment by xinyuezhao** [comment] 2022-04-04 17:16
Hi @apellini ,
thanks for providing this playbook. But until now we are not able to reproduce this issue.
After running the playbook, we didn't detect any change in template bd.

Would you mind providing details of every elements related to this issue and detailed steps how to reproduce the issue? 
And also exact content of the bd before and after static port configuration.

Or if you have a support contract with Cisco, you can also open a case in TAC where we can tract and escalate your issue better

**Comment by apellini** [comment] 2022-04-04 17:21
On our side we see that it happen only after static port configuration. The issue is still active.
I could open a TAC to track.

**Comment by lhercot** [comment] 2022-04-05 17:08
Yes please open a TAC case thanks.

**Comment by apellini** [comment] 2022-04-06 09:57
TAC Case: 693367915

**Comment by lhercot** [comment] 2022-06-04 09:59
Closing as TAC case is now closed.

**Closed by lhercot** 2022-06-04 09:59 UTC
