### ISSUE TITLE
Failed to deploy mso_schema_template_bd_subnet (Error: Provider produced inconsistent result after apply)

### ISSUE THREAD

**Issue by christung16** [CiscoDevNet/terraform-provider-mso#13] opened 2021-03-01 16:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
❯ terraform -v
Terraform v0.14.6
+ provider registry.terraform.io/ciscodevnet/mso v0.1.5

### MSO version
V 3.1.1g

### APIC version and APIC Platform for Site Level Resources
V 5.1.3e

### Affected Resource(s)

mso_schema_template_bd_subnet

### Terraform Configuration Files

terraform {
  required_providers {
    mso = {
      source = "CiscoDevNet/mso"
    }
  }
}

provider "mso" {
  username = var.user.username
  password = var.user.password
  url      = var.user.url
  insecure = true
}

data "mso_site" "site1" {
  name  = "28lab-site1-aciproduction"
}

locals {
  test_site_id = data.mso_site.site1.id
  test_tenant_id = mso_tenant.TN_test_Bed.id
  test_template_name = var.template_name
  test_schema_id = mso_schema.TN_test_Bed_Schema.id
  test_vrf_name = mso_schema_template_vrf.VRF-DMZ-IT-A.name
  test_anp_name = mso_schema_template_anp.WINDOWS-AP.name
  test_WINDOWS_bd_name = mso_schema_template_bd.WINDOWS-BD.name
  test_WINDOWS_common_bd_name = mso_schema_template_bd.WINDOWS-Common-BD.name
}

resource "mso_tenant" "TN_test_Bed" {
    name = "TN_test_Bed"
    display_name = "TN_test_Bed"
    description = "Tenant for TEST Bedting created by Terraform"
    site_associations {
      site_id = local.test_site_id
    }
}

resource "mso_schema" "TN_test_Bed_Schema" {
  name = "TN_test_Bed_Schema"
  template_name = local.test_template_name
  tenant_id = local.test_tenant_id
}

resource "mso_schema_template_vrf" "VRF-DMZ-IT-A" {
  name = "VRF-DMZ-IT-A"
  schema_id = local.test_schema_id
  template = local.test_template_name
  display_name = "VRF-DMZ-IT-A"
  layer3_multicast = false
  vzany = false
}

resource "mso_schema_template_bd" "WINDOWS-BD" {
  schema_id = local.test_schema_id
  template_name = local.test_template_name
  name = "WINDOWS-BD"
  display_name = "WINDOWS-BD"
  vrf_name = local.test_vrf_name
}

resource "mso_schema_template_bd_subnet" "WINDOWS-BD-subnet1" {
  schema_id = local.test_schema_id
  template_name = local.test_template_name
  bd_name = local.test_WINDOWS_bd_name
  ip = "192.168.19.254/24"
  scope = "public"
  description = "Subnet1 for WINDOWS-BD"
  shared = true
}

resource "mso_schema_template_bd_subnet" "WINDOWS-BD-subnet2" {
  schema_id = local.test_schema_id
  template_name = local.test_template_name
  bd_name = local.test_WINDOWS_bd_name
  ip = "192.168.64.254/24"
  scope = "public"
  description = "Subnet2 for WINDOWS-BD"
  shared = true
}

resource "mso_schema_template_bd" "WINDOWS-Common-BD" {
  schema_id = local.test_schema_id
  template_name = local.test_template_name
  name = "WINDOWS-Common-BD"
  display_name = "WINDOWS-Common-BD"
  vrf_name = local.test_vrf_name
 
}

resource "mso_schema_template_anp" "WINDOWS-AP" {
  schema_id = local.test_schema_id
  template = local.test_template_name
  name = "WINDOWS-AP"
  display_name = "WINDOWS-AP"
}

resource "mso_schema_template_anp_epg" "WINDOWS-nonDB-EPG" {
  schema_id = local.test_schema_id
  template_name = local.test_template_name
  anp_name = local.test_anp_name
  name = "WINDOWS-nonDB-EPG"
  bd_name = local.test_WINDOWS_bd_name
  vrf_name = local.test_vrf_name
  display_name = "WINDOWS-nonDB-EPG"
}

resource "mso_schema_template_anp_epg" "WINDOWS-Common-EPG" {
  schema_id = local.test_schema_id
  template_name = local.test_template_name
  anp_name = local.test_anp_name
  name = "WINDOWS-Common-EPG"
  bd_name = local.test_WINDOWS_common_bd_name
  vrf_name = local.test_vrf_name
  display_name = "WINDOWS-Common-EPG" 
}

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

❯ terraform apply -auto-approve
mso_tenant.TN_test_Bed: Creating...
mso_tenant.TN_test_Bed: Creation complete after 1s [id=603d1c3855000096d8e1ae22]
mso_schema.TN_test_Bed_Schema: Creating...
mso_schema.TN_test_Bed_Schema: Creation complete after 0s [id=603d1c385500009dd8e1ae23]     
mso_schema_template_anp.WINDOWS-AP: Creating...
mso_schema_template_vrf.VRF-DMZ-IT-A: Creating...
mso_schema_template_vrf.VRF-DMZ-IT-A: Creation complete after 0s [id=VRF-DMZ-IT-A]
mso_schema_template_bd.WINDOWS-Common-BD: Creating...
mso_schema_template_bd.WINDOWS-BD: Creating...
mso_schema_template_anp.WINDOWS-AP: Creation complete after 0s [id=WINDOWS-AP]
mso_schema_template_bd.WINDOWS-Common-BD: Creation complete after 0s [id=WINDOWS-Common-BD] 
mso_schema_template_anp_epg.WINDOWS-Common-EPG: Creating...
mso_schema_template_anp_epg.WINDOWS-Common-EPG: Creation complete after 0s [id=WINDOWS-Common-EPG]

Error: Provider produced inconsistent result after apply

When applying changes to mso_schema_template_bd.WINDOWS-BD, provider
"registry.terraform.io/ciscodevnet/mso" produced an unexpected new value: Root
resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by lhercot** [comment] 2021-04-09 00:33
Probable duplicate of #3

**Comment by lhercot** [comment] 2021-10-29 19:09
Closing as duplicate #3 
We will update #3 when we get this fixed

**Closed by lhercot** 2021-10-29 19:09 UTC
Labels: bug, duplicate
