### ISSUE TITLE
mso provider: we should not have to use resource "mso_schema_site_vrf" to be able to associate AWS cloud region to VRF

### ISSUE THREAD

**Issue by soumukhe** [CiscoDevNet/terraform-provider-mso#80] opened 2021-12-06 20:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

# Versions
ND: 2.1.1e
NDO : 3.6(0.88)
Terraform: v1.0.11
mso_plugin: v0.3.2

# Description of problem:
We should be able to associate the VRF to region from Site Loal Template without this block. If you follow the UI workflow, you bring up a VRF in the Template, then go to Site Local Template and associate the region configurations with the VRF.  Why do we need to have the resource "mso_schema_site_vrf". ?

# Configuration without "mso_schema_site_vrf"
```hcl
data "mso_site" "aws_site10" {
  name = var.aws_aws_site10_name
}

# create a tenant and associate users
resource "mso_tenant" "tenant" {
  name         = var.tenant_stuff.tenant_name
  display_name = var.tenant_stuff.display_name
  description  = var.tenant_stuff.description
  site_associations {
    site_id           = data.mso_site.aws_site10.id
    vendor            = "aws"
    aws_account_id    = var.awsstuff.aws_account_id
    aws_access_key_id = var.awsstuff.aws_access_key_id
    aws_secret_key    = var.awsstuff.aws_secret_key
  }
  user_associations { user_id = var.user_associations }
  user_associations { user_id = "ff880b89aa55edba5bc5d6490af589da0f8028b3fccbcc65dcb36c6b219e0663" }
  # for remote users, get userID, https://{msoIP}/mso/api/v1/tenants  Terraform Import does not work for ND based NDO
  #  bug opened: https://github.com/CiscoDevNet/terraform-provider-mso/issues/79
}

### create template and associate with Schema

resource "mso_schema" "schema1" {
  depends_on    = [mso_tenant.tenant]
  name          = var.schema.schema1
  template_name = var.schema.template_name1
  tenant_id     = mso_tenant.tenant.id
}

#### Associate Schema / template with Site

resource "mso_schema_site" "aws_site10" {
  depends_on    = [mso_schema.schema1]
  schema_id     = mso_schema.schema1.id
  site_id       = data.mso_site.aws_site10.id
  template_name = var.schema.template_name1

}

### Create VRF

# First create the VRF
resource "mso_schema_template_vrf" "vrf1" {
  depends_on = [mso_schema_site.aws_site10]
  schema_id  = mso_schema.schema1.id
  #template_name = var.schema.template_name1
  template         = mso_schema.schema1.template_name
  name             = var.schema.vrf_name1
  display_name     = var.schema.vrf_name1
  layer3_multicast = false
  vzany            = false
}

####  Associate with Region and zones in Site Local Templates
resource "mso_schema_site_vrf_region" "vrfRegion" {
  depends_on         = [mso_schema_template_vrf.vrf1]
  schema_id          = mso_schema.schema1.id
  template_name      = var.schema.template_name1
  site_id            = data.mso_site.aws_site10.id
  vrf_name           = var.schema.vrf_name1
  region_name        = "us-east-1"
  vpn_gateway        = false
  hub_network_enable = true
  hub_network = {
    name        = "TGW"
    tenant_name = "infra"
  }
  cidr {
    cidr_ip = "10.140.0.0/16"
    primary = true
    subnet {
      ip    = "10.140.1.0/24"
      zone  = "us-east-1a"
      usage = "gateway"
    }

    subnet {
      ip    = "10.140.2.0/24"
      zone  = "us-east-1b"
      usage = "gateway"
    }

    subnet {
      ip   = "10.140.3.0/24"
      zone = "us-east-1b"
      #usage = ""
    }
  }
}

```

# Results of Run (fail):

```hcl
Plan: 1 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

mso_schema_site_vrf_region.vrfRegion: Creating...
mso_tenant.tenant: Modifying... [id=61ae67a91d00000f9abc8a97]
mso_tenant.tenant: Modifications complete after 1s [id=61ae67a91d00000f9abc8a97]
╷
│ Error: "Resource Not Found: VrfDelta with name vrf1 not found in List()"{}
│ 
│   with mso_schema_site_vrf_region.vrfRegion,
│   on resources.tf line 73, in resource "mso_schema_site_vrf_region" "vrfRegion":
│   73: resource "mso_schema_site_vrf_region" "vrfRegion" {
│ 
╵
```
# Trying with resource "mso_schema_site_vrf" in addition:

```hcl
data "mso_site" "aws_site10" {
  name = var.aws_aws_site10_name
}


resource "mso_tenant" "tenant" {
  name         = var.tenant_stuff.tenant_name
  display_name = var.tenant_stuff.display_name
  description  = var.tenant_stuff.description
  site_associations {
    site_id           = data.mso_site.aws_site10.id
    vendor            = "aws"
    aws_account_id    = var.awsstuff.aws_account_id
    aws_access_key_id = var.awsstuff.aws_access_key_id
    aws_secret_key    = var.awsstuff.aws_secret_key
  }
  user_associations { user_id = var.user_associations }
  user_associations { user_id = "ff880b89aa55edba5bc5d6490af589da0f8028b3fccbcc65dcb36c6b219e0663" }
  # for remote users, get userID, https://{msoIP}/mso/api/v1/tenants  Terraform Import does not work for ND based NDO
}

### create template and associate with Schema

resource "mso_schema" "schema1" {
  depends_on    = [mso_tenant.tenant]
  name          = var.schema.schema1
  template_name = var.schema.template_name1
  tenant_id     = mso_tenant.tenant.id
}

#### Associate Schema / template with Site

resource "mso_schema_site" "aws_site10" {
  depends_on    = [mso_schema.schema1]
  schema_id     = mso_schema.schema1.id
  site_id       = data.mso_site.aws_site10.id
  template_name = var.schema.template_name1

}

### Create VRF
/**
#Seems like I have to do both "mso_schema_template_vrf" and "mso_schema_site_vrf" for this to work
**/

# First create the VRF
resource "mso_schema_template_vrf" "vrf1" {
  depends_on = [mso_schema_site.aws_site10]
  schema_id  = mso_schema.schema1.id
  #template_name = var.schema.template_name1
  template         = mso_schema.schema1.template_name
  name             = var.schema.vrf_name1
  display_name     = var.schema.vrf_name1
  layer3_multicast = false
  vzany            = false
}

#Why is this needed ?  We should be able to associate the VRF to region from Sitel Loal Template without this block
resource "mso_schema_site_vrf" "aws_site" {
  depends_on = [mso_schema_template_vrf.vrf1]
  schema_id  = mso_schema.schema1.id
  template_name = mso_schema_site.aws_site10.template_name
  site_id       = data.mso_site.aws_site10.id
  vrf_name = var.schema.vrf_name1
}



####  Associate with Region and zones in Site Local Templates
resource "mso_schema_site_vrf_region" "vrfRegion" {
  depends_on         = [mso_schema_site_vrf.aws_site]
  schema_id          = mso_schema.schema1.id
  template_name      = var.schema.template_name1
  site_id            = data.mso_site.aws_site10.id
  vrf_name           = var.schema.vrf_name1
  region_name        = "us-east-1"
  vpn_gateway        = false
  hub_network_enable = true
  hub_network = {
    name        = "TGW"
    tenant_name = "infra"
  }
  cidr {
    cidr_ip = "10.140.0.0/16"
    primary = true
    subnet {
      ip    = "10.140.1.0/24"
      zone  = "us-east-1a"
      usage = "gateway"
    }

    subnet {
      ip    = "10.140.2.0/24"
      zone  = "us-east-1b"
      usage = "gateway"
    }

    subnet {
      ip   = "10.140.3.0/24"
      zone = "us-east-1b"
      #usage = ""
    }

  }
}
```
# Results of Run (pass):
```hcl 
Plan: 2 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

mso_schema_site_vrf.aws_site: Creating...
mso_tenant.tenant: Modifying... [id=61ae67a91d00000f9abc8a97]
mso_schema_site_vrf.aws_site: Creation complete after 0s [id=vrf1]
mso_schema_site_vrf_region.vrfRegion: Creating...
mso_schema_site_vrf_region.vrfRegion: Creation complete after 0s [id=us-east-1]
mso_tenant.tenant: Modifications complete after 1s [id=61ae67a91d00000f9abc8a97]

Apply complete! Resources: 2 added, 1 changed, 0 destroyed.
```

**Comment by lhercot** [comment] 2021-12-13 09:23
Duplicate of #83 see message there for explanation.

**Closed by lhercot** 2021-12-13 09:23 UTC
