### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by qbeusz** [CiscoDevNet/terraform-provider-mso#39] opened 2021-07-28 13:36 UTC
Community Note

    Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
    Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
    If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform Version

Terraform v1.0.3
on linux_amd64

    provider registry.terraform.io/ciscodevnet/mso v0.2.1

MSO version

    V 3.3(1e)

APIC version and APIC Platform for Site Level Resources

    V 5.2(1g) on-prem
    V 5.1(2e) cloud-azure

Affected Resource(s)

### Terraform Configuration Files

resource "mso_schema_template" "TF_TEMPLATE_TF1_AZURE" {
  schema_id = mso_schema.RKB_SCHEMA_TF_1.id
  name = "TF_TEMPLATE_TF1_AZURE"
  display_name = "TF_TEMPLATE_TF1_AZURE"
  tenant_id     = mso_tenant.TENANT_MSO_RKB_TF.id
}

resource "mso_schema_template" "TF_TEMPLATE_TF1_ONPREM" {

  schema_id = mso_schema.RKB_SCHEMA_TF_1.id
  name = "TF_TEMPLATE_TF1_ONPREM"
  display_name = "TF_TEMPLATE_TF1_ONPREM"
  tenant_id     = mso_tenant.TENANT_MSO_RKB_TF.id
}

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

mso_schema_template.TF_TEMPLATE_TF1_AZURE: Creation complete after 0s [id=TF_TEMPLATE_TF1_AZURE]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to mso_schema_template.TF_TEMPLATE_TF1_ONPREM, provider "provider[\"registry.terraform.io/ciscodevnet/mso\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

**Comment by lhercot** [comment] 2021-08-28 02:08
This is issue is due to a concurrency issue in MSO API.
It should go away if you use -parallelism=1 with you apply and destroy.

**Comment by lhercot** [comment] 2021-08-30 15:45
Duplicate of #3

**Comment by lhercot** [comment] 2021-09-20 17:03
Closing as duplicate of #3 and using #3 to track the problem

**Closed by lhercot** 2021-09-20 17:03 UTC
Labels: bug
