### ISSUE TITLE
mso_site_schema - Error: Provider produced inconsistent result after apply with more than 1 site

### ISSUE THREAD

**Issue by damcfarl** [CiscoDevNet/terraform-provider-mso#44] opened 2021-08-28 20:08 UTC
terraform --version
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/ciscodevnet/mso v0.2.1

MSO 3.1(1i)
APICs 5.2(1g)

my main.tf

### Terraform Configuration Files

# Define an MSO Tenant Resource.
data "mso_tenant" "tenant_obj" {
    name         = var.tenant_name
    display_name = var.tenant_name
}

# Define an MSO Schema Resource.
data  "mso_schema" "schema_obj" {
    name          = var.schema
}

data "mso_site" "site1_obj" {
    name          = var.site1_name
}

data "mso_site" "site2_obj" {
    name          = var.site2_name
}

resource "mso_schema_site" "schema_site1_obj" {
  schema_id       =  data.mso_schema.schema_obj.id
  site_id         =  data.mso_site.site1_obj.id
  template_name   =  var.template_name
}

/* Resource issue with multiple sites
resource "mso_schema_site" "schema_site2_obj" {
  schema_id       =  data.mso_schema.schema_obj.id
  site_id         =  data.mso_site.site2_obj.id
  template_name   =  var.template_name
}
*/

If I don't stub out the second site definition, I'll get this error during "terraform apply". I receive no error during "terraform plan"

[~/Documents/terraform/cli_terraform/mso/2a_add_sites]\> terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # mso_schema_site.schema_site1_obj will be created
  + resource "mso_schema_site" "schema_site1_obj" {
      + id            = (known after apply)
      + schema_id     = "612a90b96300004fd74bf29e"
      + site_id       = "6112ba880401001801d79f31"
      + template_name = "terraform_template"
    }

  # mso_schema_site.schema_site2_obj will be created
  + resource "mso_schema_site" "schema_site2_obj" {
      + id            = (known after apply)
      + schema_id     = "612a90b96300004fd74bf29e"
      + site_id       = "6112bb1e0401003c01d79f32"
      + template_name = "terraform_template"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

mso_schema_site.schema_site1_obj: Creating...
mso_schema_site.schema_site2_obj: Creating...
mso_schema_site.schema_site1_obj: Creation complete after 0s [id=6112ba880401001801d79f31]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to mso_schema_site.schema_site2_obj, provider
│ "provider[\"registry.terraform.io/ciscodevnet/mso\"]" produced an unexpected new value: Root resource
│ was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Debug Output

git@github.com:damcfarl/gist.git

### Expected Behavior

All sites should have added

### Actual Behavior

Only the first defined site is added

### Steps to Reproduce

Add or remove the second site to mso_schema_site

**Comment by lhercot** [comment] 2021-08-29 01:20
This issue is due to a concurrency issue in MSO API.
It should go away if you use -parallelism=1 with you apply and destroy.

**Comment by damcfarl** [comment] 2021-08-29 02:33
Lionel,

Yes, that worked. Thank you

If I may trouble you for another item. I’m trying to deploy the templates to the sites

In Postman, I do something like this:

Method: GET
URL: {{url}}execute/schema/{{schema_id}}/template/{{template_name}}

If I run this in Postman, the template is deployed

If I run from the UI, the template is deployed

***@***.***

I haven’t found a terraform plugin to preform the deploy. I may not be looking hard enough

I’ve tried to replicate the Postman GET request with a mso_rest.

It fails, as the payload is empty, but, also fails if the GET does not contain a payload

[~/Documents/terraform/cli_terraform/mso/2b_Deploy_Templates]\> terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # mso_rest.deploy_templates will be created
  + resource "mso_rest" "deploy_templates" {
      + id      = (known after apply)
      + method  = "GET"
      + path    = "api/v1/schemas/excute/612ae9d1630000e0eb4bf2a1/template/template_tenant"
      + payload = jsonencode(
            [
              + {},
            ]
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

mso_rest.deploy_templates: Creating...
╷
│ Error: "Not Found"{}
│
│   with mso_rest.deploy_templates,
│   on main.tf line 20, in resource "mso_rest" "deploy_templates":
│   20: resource "mso_rest" "deploy_templates" {


[~/Documents/terraform/cli_terraform/mso/2b_Deploy_Templates]\> terraform plan
╷
│ Error: Incorrect attribute value type
│
│   on main.tf line 23, in resource "mso_rest" "deploy_templates":
│   23:    payload = [{}]
│
│ Inappropriate value for attribute "payload": string required.




Any clues as to what I am doing wrong?

Thank you again. I’ve spent many hours trying different .tf variations trying to resolve add multiple sites to the template.

I have similar issues in Ansible, I ended up putting a 5 sec delay between each site addition. I’m sure there is a better way

Thank you again,

Dave



From: Lionel Hercot ***@***.***>
Date: Saturday, August 28, 2021 at 6:20 PM
To: CiscoDevNet/terraform-provider-mso ***@***.***>
Cc: Dave Mcfarland (damcfarl) ***@***.***>, Author ***@***.***>
Subject: Re: [CiscoDevNet/terraform-provider-mso] mso_site_schema - Error: Provider produced inconsistent result after apply with more than 1 site (#44)

This issue is due to a concurrency issue in MSO API.
It should go away if you use -parallelism=1 with you apply and destroy.

**Comment by lhercot** [comment] 2021-08-30 15:42
Did you try the resource mso_schema_template_deploy https://registry.terraform.io/providers/CiscoDevNet/mso/latest/docs/resources/schema_template_deploy ?

As you confirmed, your issue is fixed and we are tracking this issue with other issues, I will close this one.

**Comment by lhercot** [comment] 2021-08-30 15:43
Duplicate of #3

**Closed by lhercot** 2021-08-30 15:42 UTC
Labels: bug

**Comment by damcfarl** [comment] 2021-08-30 15:45
Lionel,

Yes, that resource worked to deploy

Thank you,

Dave

From: Lionel Hercot ***@***.***>
Date: Monday, August 30, 2021 at 8:42 AM
To: CiscoDevNet/terraform-provider-mso ***@***.***>
Cc: Dave Mcfarland (damcfarl) ***@***.***>, Author ***@***.***>
Subject: Re: [CiscoDevNet/terraform-provider-mso] mso_site_schema - Error: Provider produced inconsistent result after apply with more than 1 site (#44)

Did you try the resource mso_schema_template_deploy https://registry.terraform.io/providers/CiscoDevNet/mso/latest/docs/resources/schema_template_deploy ?

As you confirmed, your issue is fixed and we are tracking this issue with other issues, I will close this one.
